# Site settings
title: Nathan Henry Wallace
email: nathan@nahrwl.me
description: > # this means to ignore newlines until "baseurl:"
  Nathan Henry Wallace is a designer and developer
  based out of Los Angeles.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nahrwl.me" # the base hostname & protocol for your site
twitter_username:  nahrwl
github_username:   nahrwl
linkedin_username: nahrwl

# Build settings
markdown: kramdown
